accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from fotodnya.views import *
from fotodnya.views import BlogDetailView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', indexPage),
    path('about', aboutPage),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('post/<int:pk>/', BlogDetailView.as_view(), name='post_detail'),
    path('static/images/favicon.ico', RedirectView.as_view(url='static/images/favicon.ico'), name='favicon'),
    #CreateView.as_view(model=fotoNews, success_url="post/<int:pk>/")
]

accounts/models.py
from django.db import models

# Create your models here.

fotodnya/models.py
from django.db import models
from django.urls import path

class fotoNews(models.Model):
    title = models.CharField(max_length=120)
    img = models.ImageField(upload_to='static/images/', null=True, blank=True, default='static/images/default.jpg')
    author = models.CharField(max_length=120, blank=True)
    url_from = models.URLField(max_length=300, default='http://fotodnya.site', blank=True)
    timepostdate = models.DateTimeField(auto_now=False, auto_now_add=False, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.title}'


class comments_fn(models.Model):
    fotoNews = models.ForeignKey(fotoNews, related_name='comments', on_delete=models.CASCADE)
    comment = models.TextField(blank=True, null=True)
    name = models.CharField(max_length=80)
    email = models.EmailField(default='none')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.fotoNews, self.comment)

fotodnya/forms.py
from django import forms
from django.forms import Textarea, TextInput
from django.http import request

from .models import comments_fn
from django.db import models

class formPropose(forms.Form):
    Заголовок = forms.CharField(max_length=220)
    Информация = forms.CharField(widget=forms.Textarea)



class CommentForm(forms.ModelForm):
    class Meta:
        model = comments_fn
        fields = ('comment', 'name', 'fotoNews')
        widgets = {
            "name": Textarea(attrs={
                'class': 'username_get',
                'value': '{{ request.user.username.title }}'
            })
        }

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

fotodnya/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import FormMixin

from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CommentForm



def indexPage(request):
    object_list = list(reversed(fotoNews.objects.all()))
    paginator = Paginator(object_list, 8)  # 8 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'index.html',
                  {'page': page,
                   'posts': posts})


class BlogDetailView(DetailView, FormMixin):
    model = fotoNews
    template_name = 'post_detail.html'
    form_class = CommentForm
    success_url = '.#comments'

    def get_context_data(self, **kwargs):
        context = super(BlogDetailView, self).get_context_data(**kwargs)
        context['comments'] = comments_fn.objects.all()
        context['CommentForm'] = CommentForm()
        # And so on for more models
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        CommentForm = self.get_form()
        if CommentForm.is_valid():
            return self.form_valid(CommentForm)
        else:
            return self.form_invalid(CommentForm)

    def form_valid(self, CommentForm):
        CommentForm.instance.post = self.object
        CommentForm.instance.author = self.request.user
        CommentForm.save()
        return super().form_valid(CommentForm)


def aboutPage(request):
    return render(request, 'about.html')

templates/about.html
{% extends 'base.html' %}

{% block content %}
    <div class="post_foto">
        <h2>О нас</h2>
        <p>Фотографии, использованные на сайте принадлежат их правообладателям.<br>
            Если Вы считаете, что мы не можем использовать Ваше фото - пожалуйста, напишите нам.</p>
        <p>По любым вопросам: juv4ik@gmail.com</p>
        <!--<form method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="send">
        </form>-->
         <hr>
    </div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}fotoNews{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/jquery-3.6.0.js' %}"></script>
    <script src="{% static 'js/scrolltop.js' %}"></script>
</head>
<body>
<div id="main">
    <div id="header">
        <a class="logo" href="/"><h1>Фото дня</h1></a>
        <hr>
        <div id="under_header">
            <div class="menu">
                <p><a href="/">Главная</a> | <a href="/about">О нас</a></p>
            </div>
        <div class="user_login">
            {% if user.is_authenticated %}
                {% if user.is_staff %}
            <p>&#128274; {{ user.username }} <a href="{% url 'logout' %}">Выйти</a> | <a href="http://127.0.0.1:8000/admin">админка</a></p>
                {% else %}
                <p>&#128274; {{ user.username }} <a href="{% url 'logout' %}">Выйти</a></p>
                {% endif %}
            {% else %}
                <p>Вы не залогинены. <a href="{% url 'login' %}">Вход</a> | <a href="{% url 'signup' %}">Регистрация</a></p>
            {% endif %}
        </div>
        </div>

    </div>
    {% block content %}
    {% endblock content %}
    <div id="footer">
        <p>&copy; 2021 <a href ="/">fotodnya</a></p>
    </div>

    <a id="back2Top" href="#" title="подняться вверх">&#10148;</a>
</div>


</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="post_foto">
        {% for post in posts %}
            {% if post.active == 1 %}
        <h2><a href="{% url 'post_detail' post.pk %}">{{ post.title }}</a></h2>
        <p>{{ post.author }}</p>
        <img src="{{ post.img.url }}" width="750px">
        <p><a href="/">{{ post.url_from }}</a></p>
        <p>{{ post.timepostdate }}</p>
        <p class="news-text">{{ post.description }}</p>
        <hr class="news">
        {% endif %}
        {% endfor %}
    </div>
    {% include "pagination.html" with page=posts %}
{% endblock content %}

templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Назад</a>
        {% endif %}
        <span class="current">
            Стр. {{ page.number }} из {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Далее</a>
        {% endif %}
    </span>
</div>

templates/post_detail.html
{% extends 'base.html' %}

{% block title %}
{{ fotonews.title }}
{% endblock %}

{% block content %}
<div class="post_foto">
    <h2>{{ fotonews.title }}</h2>
    <p>фото: {{ fotonews.author }}</p>
    <img src="{{ fotonews.img.url }}" width="750px">
    <p>источник: <a href="/">{{ fotonews.url_from }}</a></p>
    <p>{{ fotonews.timepostdate }}</p>
    <p class="news-text">{{ fotonews.description }}</p>
    <div id="comments">
        <a name="comments"></a><h3>Комментарии:</h3>
        {% if user.is_authenticated %}
        <form method="post" id="comment_form">
            {% csrf_token %}
<div class="fieldWrapper">
    {{ form.comment.errors }}
    <textarea id="id_comment" name="comment" cols="50" rows="10" placeholder="Ваше мнение, {{ user.username }}" required></textarea>
</div>
<div class="fieldWrapper">
    {{ form.name.errors }}
    <textarea id="id_name" name="name" style="display: none;">{{ user.username }}</textarea>
</div>
<div class="fieldWrapper">
    {{ form.fotoNews.errors }}
    <textarea id="id_fotoNews" name="fotoNews" style="display: none;">{{ fotonews.pk }}</textarea>
    <input type="submit" value="Оставить комментарий!">
</div>

        </form>
        {% else %}
        <p>чтобы оставлять комментарии, необходимо <a href="/accounts/login/">залогиниться</a></p>
        {% endif %}
        {% for i in comments %}
            {% if i.fotoNews_id == fotonews.pk %}
                {% if i.active == 1 %}
                    <div class="comment">
                        <p class="comment_by">{{ i.name }}, {{i.created }}:</p>
                        <p class="comment_text">{{ i.comment }}</p>
                    </div>
                {% endif %}
            {% endif %}
        {% endfor %}
    </div>
    <hr class="news">
</div>

{% endblock content %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}
    <div class="signup">
        <h2>Регистрация</h2>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">Зарегистрироваться</button>
        </form>
    </div>
{% endblock content %}